name: Pre-merge

on: [pull_request, push]

jobs:
  reproducer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
